version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 468381101993.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=012345678910.dkr.ecr.us-west-2.amazonaws.com/hello-world
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hello .
      - docker tag hello:latest 468381101993.dkr.ecr.eu-central-1.amazonaws.com/hello:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 468381101993.dkr.ecr.eu-central-1.amazonaws.com/hello:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' 468381101993.dkr.ecr.eu-central-1.amazonaws.com:hello > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
